// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list-item': string;
  'listItem': string;
  'no-border': string;
  'noBorder': string;
}
export const cssExports: CssExports;
export default cssExports;
