// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'not-online': string;
  'notOnline': string;
  'online': string;
}
export const cssExports: CssExports;
export default cssExports;
