// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'no-list-style': string;
  'no-margin': string;
  'noListStyle': string;
  'noMargin': string;
}
export const cssExports: CssExports;
export default cssExports;
