// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'browser-address': string;
  'browser-panel': string;
  'browserAddress': string;
  'browserPanel': string;
  'dots-wrapper': string;
  'dotsWrapper': string;
  'green': string;
  'link': string;
  'red': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
