export enum payloadTypes {
  boardCreated = 'board-created',
  boardDeleted = 'board-deleted',
  createBoard = 'create-board',
  currentBoards = 'current-boards',
  error = 'error',
  errorGameHasAlreadyStarted = 'error-game-has-already-started',
  errorTooManyPlayers = 'too-many-players',
  gameReadyToStart = 'game-ready-to-start',
  gameStarted = 'game-started',
  joinedGame = 'joined-a-game',
  joinGame = 'join-game',
  leaveGame = 'leave-game',
  newPlayer = 'new-player',
  playerLeftBoard = 'player-left-board',
  refreshBoards = 'refresh-boards',
  registerUser = 'register-user',
}
