export enum payloadTypes {
  boardCreated = 'board-created',
  boardCreatedSnackSuccess = 'boardCreatedSnack-success',
  boardDeleted = 'board-deleted',
  createBoard = 'create-board',
  currentBoards = 'current-boards',
  error = 'error',
  errorGameHasAlreadyStarted = 'error-game-has-already-started',
  errorTooManyPlayers = 'too-many-players',
  gameNotAbleToStart = 'game-not-able-to-start',
  gameReadyToStart = 'game-ready-to-start',
  gameStarted = 'game-started',
  joinedBoardSnackSuccess = 'joinedBoardSnack-success',
  joinGame = 'join-game',
  leaveGame = 'leave-game',
  newPlayer = 'new-player',
  newPlayerSnackSuccess = 'playerJoinedSnack-success',
  playerLeftBoard = 'player-left-board',
  playerLeftBoardSnackInfo = 'playerLeftBoard-info',
  refreshBoards = 'refresh-boards',
  registerUser = 'register-user',
}
