// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filled': string;
  'none': string;
  'primary': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
