// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'blue': string;
  'brown': string;
  'card': string;
  'green': string;
  'grey': string;
  'none': string;
  'orange': string;
  'pink': string;
  'red': string;
}
export const cssExports: CssExports;
export default cssExports;
