// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'exploading': string;
  'icon': string;
  'logo': string;
  'menu': string;
  'out-links': string;
  'outLinks': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
